# Generated by Django 5.0.4 on 2024-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbiosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postagens',
            name='versiculo',
            field=models.TextField(),
        ),
    ]
