# Generated by Django 5.0.4 on 2024-04-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbiosapp', '0003_remove_postagens_texto_postagens_aplicacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='postagens',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proverbiosapp.temas'),
        ),
    ]
