# Generated by Django 5.0.4 on 2024-04-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbiosapp', '0004_temas_alter_postagens_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='tema',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
