# Generated by Django 5.0.4 on 2024-04-25 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbiosapp', '0005_alter_postagens_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagens',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proverbiosapp.temas'),
        ),
    ]
