# Generated by Django 5.0.4 on 2024-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbiosapp', '0006_alter_postagens_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='tema',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
