# Generated by Django 5.0.4 on 2024-04-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbiosapp', '0007_alter_temas_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Família',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
    ]
