# Generated by Django 5.0.4 on 2024-04-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proverbiosapp', '0008_amigos_emprestimo_família_investimento_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Justica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preguica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sabedoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sabio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vizinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versiculo', models.CharField(max_length=60, null=True)),
                ('contexto', models.TextField(null=True)),
                ('aplicacao', models.TextField(null=True)),
            ],
        ),
    ]
