# Generated by Django 5.0.4 on 2024-05-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proverbiosapp', '0009_disciplina_justica_preguica_sabedoria_sabio_vizinho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postagens',
        ),
        migrations.DeleteModel(
            name='Temas',
        ),
    ]
